In [1]:
# Python libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re
from bs4 import BeautifulSoup
import nltk
from nltk.corpus import wordnet
from nltk.stem.wordnet import WordNetLemmatizer
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Mohaw\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Mohaw\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Mohaw\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [2]:
#Read la data frame
df=pd.read_csv(filepath_or_buffer='QueryResults(2).csv')
df

,Title,Body,Tags,Id,Score,ViewCount,FavoriteCount,AnswerCount
0,"angular: assigning ng-options dynamically, str...",<p>I am building an inline editable form.</p>\...,<javascript><angularjs><select>,20060436,1,271.0,NaN,1.0
1,NaN,<p>I'm going to operate off the assumption tha...,NaN,20060437,1,NaN,NaN,NaN
2,NaN,<p>Use to add the textarea's classes to tinymc...,NaN,20060438,4,NaN,NaN,NaN
3,NaN,<p>It seems to me that unless the compiler can...,NaN,20060439,4,NaN,NaN,NaN
4,NaN,<blockquote>\n <p>Is the compiler free to ass...,NaN,20060440,16,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
49995,Delete files older than 24 hours and empty dir...,<p>I have these cron tasks to manage the autom...,<find><cron>,20107249,-1,2598.0,0.0,3.0
49996,MVC 4 Jquery Datepicker Initializes on Multipl...,"<p>I'm using VS2010, MVC 4 with Razor, JQuery ...",<jquery><asp.net-mvc-4><jquery-ui-datepicker>,20107251,0,154.0,NaN,0.0
49997,How to change the default redirect behaviour o...,<p>I am working on an <code>ASP.NET MVC 4</cod...,<asp.net-mvc-4><forms-authentication><simpleme...,20107253,0,584.0,NaN,0.0
49998,puppet how to manage service with only if,"<p>Can some one help me with puppet, I want to...",<service><puppet><configurationmanager>,20107254,1,2285.0,NaN,1.0
49999,construct a data frame in R from combining inf...,<p>I have a data frame consisting of two colum...,<r>,20107255,0,85.0,NaN,2.0

In [3]:
df.head(5)

,Title,Body,Tags,Id,Score,ViewCount,FavoriteCount,AnswerCount
0,"angular: assigning ng-options dynamically, str...",<p>I am building an inline editable form.</p>\...,<javascript><angularjs><select>,20060436,1,271.0,NaN,1.0
1,NaN,<p>I'm going to operate off the assumption tha...,NaN,20060437,1,NaN,NaN,NaN
2,NaN,<p>Use to add the textarea's classes to tinymc...,NaN,20060438,4,NaN,NaN,NaN
3,NaN,<p>It seems to me that unless the compiler can...,NaN,20060439,4,NaN,NaN,NaN
4,NaN,<blockquote>\n <p>Is the compiler free to ass...,NaN,20060440,16,NaN,NaN,NaN

In [4]:
df.tail(5)

,Title,Body,Tags,Id,Score,ViewCount,FavoriteCount,AnswerCount
49995,Delete files older than 24 hours and empty dir...,<p>I have these cron tasks to manage the autom...,<find><cron>,20107249,-1,2598.0,0.0,3.0
49996,MVC 4 Jquery Datepicker Initializes on Multipl...,"<p>I'm using VS2010, MVC 4 with Razor, JQuery ...",<jquery><asp.net-mvc-4><jquery-ui-datepicker>,20107251,0,154.0,NaN,0.0
49997,How to change the default redirect behaviour o...,<p>I am working on an <code>ASP.NET MVC 4</cod...,<asp.net-mvc-4><forms-authentication><simpleme...,20107253,0,584.0,NaN,0.0
49998,puppet how to manage service with only if,"<p>Can some one help me with puppet, I want to...",<service><puppet><configurationmanager>,20107254,1,2285.0,NaN,1.0
49999,construct a data frame in R from combining inf...,<p>I have a data frame consisting of two colum...,<r>,20107255,0,85.0,NaN,2.0

In [5]:
df.sample(20)

,Title,Body,Tags,Id,Score,ViewCount,FavoriteCount,AnswerCount
19387,NaN,"<p>I am the developer of <a href=""https://gith...",NaN,39118307,7,NaN,NaN,NaN
26446,NaN,<p>I don't remember offhand if there's a built...,NaN,1123040,6,NaN,NaN,NaN
31075,NaN,"<p>With access to the CSV generation, here's o...",NaN,57798222,0,NaN,NaN,NaN
234,Complex number computational error grows as th...,"<p>If I have two small complex matrices, the c...",<python-3.x><precision><complex-numbers><compu...,57767349,1,199.0,NaN,1.0
30400,Looping to display on LEDs HCS12 microcontroller,<p>hello i am trying to do a loop in assembly ...,<assembly><microcontroller><68hc12>,20100772,0,1899.0,NaN,2.0
47945,"What does this function do , Haskell",<p>I need an algorithm that converts bin to de...,<template-haskell>,20106612,0,72.0,NaN,1.0
44562,NaN,<p>Your code has a serious problem. Specifica...,NaN,20105588,6,NaN,NaN,NaN
27341,NaN,<p>This might achieve what you're after:</p>\n...,NaN,20070287,0,NaN,NaN,NaN
37845,NaN,<p>I presume that you want to convert your col...,NaN,1163645,1,NaN,NaN,NaN
13378,Find maximum element from two arrays,<p>I need to find maximum element from two arr...,<java>,57770879,0,3983.0,0.0,5.0
16590,NaN,<p>Ok i was using an old version. Everything i...,NaN,39117606,0,NaN,NaN,NaN
21649,oauth_callback on Android,<p>I created a Twitter app I need user of my A...,<android><twitter><oauth>,1121329,6,6804.0,0.0,1.0
33962,"React Component, validate the child's componen...",<p>Let's say I have a reactJS component with a...,<javascript><reactjs>,39145971,1,5948.0,0.0,2.0
32027,How can I create a .properties file in folder/...,<p>I'm using properties files in my program. I...,<java><netbeans><jar>,57798517,0,130.0,NaN,0.0
28094,NaN,<p>In order to flesh this out with more info. ...,NaN,1123866,1,NaN,NaN,NaN
15727,NaN,<blockquote>\n <p>but in the above case it is...,NaN,1118928,2,NaN,NaN,NaN
12888,insertion sort in objective c is not returning...,<pre><code>arr = [NSMutableArray array];\n[arr...,<objective-c><nsmutablearray><insertion-sort>,20064925,1,116.0,NaN,2.0
15325,Do zombies exist ... in .NET?,<p>I was having a discussion with a teammate a...,<c#><.net><multithreading><load><zombie-process>,20065780,406,28688.0,0.0,7.0
32304,Not able to Connect to hbase through phoenix,<p>When i am trying to connect to hbase throug...,<hadoop><hbase>,39145514,0,547.0,NaN,1.0
22251,In what way is this jStorage Object different ...,"<p>I am working on an e-shop, where an item in...",<jquery><object><jstorage>,39119130,0,241.0,NaN,1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          17920 non-null  object
 1   Body           49970 non-null  object
 2   Tags           17920 non-null  object
 3   Id             50000 non-null  int64
 4   Score          50000 non-null  int64
 5   ViewCount      17920 non-null  float64
 6   FavoriteCount  5079 non-null   float64
 7   AnswerCount    17920 non-null  float64
dtypes: float64(3), int64(2), object(3)
memory usage: 3.1+ MB

In [7]:
df.dtypes.value_counts()

object     3
float64    3
int64      2
Name: count, dtype: int64

In [8]:
df.nunique()

Title            17918
Body             49954
Tags             14328
Id               50000
Score              309
ViewCount         5772
FavoriteCount        1
AnswerCount         35
dtype: int64

# NaN et duplicated

In [9]:
df.isna().sum()

Title            32080
Body                30
Tags             32080
Id                   0
Score                0
ViewCount        32080
FavoriteCount    44921
AnswerCount      32080
dtype: int64

In [10]:
df.isna().mean()

Title            0.64160
Body             0.00060
Tags             0.64160
Id               0.00000
Score            0.00000
ViewCount        0.64160
FavoriteCount    0.89842
AnswerCount      0.64160
dtype: float64

In [11]:
df.isna().mean().sort_values()

Id               0.00000
Score            0.00000
Body             0.00060
Title            0.64160
Tags             0.64160
ViewCount        0.64160
AnswerCount      0.64160
FavoriteCount    0.89842
dtype: float64

In [12]:
df.duplicated().sum()

0

In [18]:
#On garde que les variables les plus importantes:
df=df[['Body','Title','Tags']]
df

,Body,Title,Tags
0,<p>I am building an inline editable form.</p>\...,"angular: assigning ng-options dynamically, str...",<javascript><angularjs><select>
1,<p>I'm going to operate off the assumption tha...,NaN,NaN
2,<p>Use to add the textarea's classes to tinymc...,NaN,NaN
3,<p>It seems to me that unless the compiler can...,NaN,NaN
4,<blockquote>\n <p>Is the compiler free to ass...,NaN,NaN
...,...,...,...
49995,<p>I have these cron tasks to manage the autom...,Delete files older than 24 hours and empty dir...,<find><cron>
49996,"<p>I'm using VS2010, MVC 4 with Razor, JQuery ...",MVC 4 Jquery Datepicker Initializes on Multipl...,<jquery><asp.net-mvc-4><jquery-ui-datepicker>
49997,<p>I am working on an <code>ASP.NET MVC 4</cod...,How to change the default redirect behaviour o...,<asp.net-mvc-4><forms-authentication><simpleme...
49998,"<p>Can some one help me with puppet, I want to...",puppet how to manage service with only if,<service><puppet><configurationmanager>
49999,<p>I have a data frame consisting of two colum...,construct a data frame in R from combining inf...,<r>

In [19]:
df.shape

(50000, 3)

In [20]:
df.isna().sum()

Body        30
Title    32080
Tags     32080
dtype: int64

In [21]:
df.describe(include=object)

,Body,Title,Tags
count,49970,17920,17920
unique,49954,17918,14328
top,DON'T EVEN THINK OF USING THIS TAG! It was bu...,Convert Memo to Text,<javascript>
freq,3,2,85

In [17]:
df.isna().sum()

Id           0
Body        30
Title    32080
Tags     32080
dtype: int64